backend:
  name: git-gateway 
  repo: BlockadeBrigade/Mary-s-Portfolio-Site
  branch: main 

  
media_folder: "/assets/WEB/upload"
public_folder: "/assets/WEB/"
media_library:
    name: uploads  

collections:

